COLLEGE_CHOICES = (
    ('Aalim Muhammed Salegh College of Engineering, Chennai', 'Aalim Muhammed Salegh College of Engineering, Chennai'),
    ('Aarupadai Veedu Institute of Technology, Kanchipuram', 'Aarupadai Veedu Institute of Technology, Kanchipuram'),
    ('Agni College of Technology, Chennai', 'Agni College of Technology, Chennai'),
    ('Aksheyaa College of Engineering, Maduranthagam', 'Aksheyaa College of Engineering, Maduranthagam'),
    ('Asan Memorial College of Engineering and Technology, Chengalpattu',
     'Asan Memorial College of Engineering and Technology, Chengalpattu'),
)

DEPARTMENT_CHOICES = (
    ('Acoustic Engineering', 'Acoustic Engineering'),
    ('Aerospace Engineering', 'Aerospace Engineering'),
    ('Aeronautical Engineering', 'Aeronautical Engineering'),
    ('Agricultural Engineering', 'Agricultural Engineering'),
    ('Automobile Engineering', 'Automobiles Engineering'),
    ('Biomedical Engineering', 'Biomedical Engineering'),
    ('Chemical Engineering', 'Chemical Engineering'),
    ('Civil Engineering', 'Civil Engineering'),
    ('Computer Engineering', 'Computer Engineering'),
    ('Computer Science and Engineering', 'Computer Science and Engineering'),
    ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'),
    ('Electrical and Electronics Engineering', 'Electrical and Electronics Engineering'),
    ('Electrical and Instrumentation Engineering', 'Electrical and Instrumentation Engineering'),
    ('Electronics and Telecommunication Engineering', 'Electronics and Telecommunication Engineering'),
    ('Electrical Engineering', 'Electrical Engineering'),
    ('Electronics Engineering', 'Electronics Engineering'),
    ('Environmental Engineering', 'Environmental Engineering'),
    ('Fashion Design', 'Fashion Design'),
    ('Food Technology', 'Food Technology'),
    ('Garment Technology', 'Garment Technology'),
    ('Industrial Biotechnology', 'Industrial Biotechnology'),
    ('Industrial Engineering', 'Industrial Engineering'),
    ('Information Technology', 'Information Technology'),
    ('Instrumentation and Control Engineering', 'Instrumentation and Control Engineering'),
    ('Instrumentation Technology', 'Instrumentation Technology'),
    ('Leather Technology', 'Leather Technology'),
    ('Marine Engineering', 'Marine Engineering'),
    ('Materials Engineering', 'Materials Engineering'),
    ('Mechanical Engineering', 'Mechanical Engineering'),
    ('Metallurgical Engineering', 'Metallurgical Engineering'),
    ('Mining Engineering', 'Mining Engineering'),
    ('Naval Architecture', 'Naval Architecture'),
    ('Nuclear Engineering', 'Nuclear Engineering'),
    ('Ocean Engineering', 'Ocean Engineering'),
    ('Petroleum Engineering', 'Petroleum Engineering'),
    ('Plastic Technology', 'Plastic Technology'),
    ('Production Engineering', 'Production Engineering'),
    ('Textile Engineering', 'Textile Engineering'),
    ('Transportation Engineering', 'Transportation Engineering'),
)
