# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-23 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop_student',
            name='transaction_id',
            field=models.CharField(default=' ', max_length=40),
            preserve_default=False,
        ),
    ]
