# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-21 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registrations', '0001_initial'),
        ('Infoquest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop_mail',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrations.workshop_student'),
        ),
        migrations.AddField(
            model_name='shortlisted_candidates',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Infoquest.events'),
        ),
        migrations.AddField(
            model_name='shortlisted_candidates',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrations.Infoquest_student'),
        ),
        migrations.AddField(
            model_name='ppt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrations.Infoquest_student'),
        ),
        migrations.AddField(
            model_name='mail_sent_students_ppt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrations.Infoquest_student'),
        ),
        migrations.AddField(
            model_name='infoquest_mail',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrations.Infoquest_student'),
        ),
        migrations.AddField(
            model_name='individual_round',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Infoquest.events'),
        ),
    ]
